In [1]:
import tensorflow as tf

In [8]:
#使用張量運算模擬神經網路
#Y=activation(X*W+b)
X = tf.Variable([[0.4, 0.2, 0.4]])
W = tf.Variable([[-0.5,-0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])
b = tf.Variable([0.1, 0.2])
XWb = tf.matmul(X,W)+b
relu_Y = tf.nn.relu(XWb) #使用relu激活函數
sigmoid_Y = tf.nn.sigmoid(XWb) #使用sigmoid激活函數

In [9]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb =', sess.run(XWb))
    print('relu_Y =', sess.run(relu_Y))
    print('sigmoid_Y =', sess.run(sigmoid_Y))

XWb = [[-0.35999998  0.28      ]]
relu_Y = [[ 0.    0.28]]
sigmoid_Y = [[ 0.41095957  0.56954622]]


In [10]:
#以亂數初始化模型的權重W和偏差b，tf.random_normal可產生常態分布的亂數矩陣
X = tf.Variable([[0.4, 0.2, 0.4]]) #1*3的輸入矩陣
W = tf.random_normal([3, 2]) #產生3*2的亂數矩陣
b = tf.random_normal([1, 2]) #產生1*2的亂數矩陣
Y = tf.nn.relu(tf.matmul(X,W)+b)

In [11]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('W =', sess.run(W))
    print('b =', sess.run(b))
    print('Y =', sess.run(Y))

W = [[ 0.01643261  1.02194643]
 [ 1.04610837 -2.64075446]
 [-1.59176743 -0.04775552]]
b = [[ 0.38080594 -0.7991665 ]]
Y = [[ 1.08476818  0.4601739 ]]


In [12]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    (_W,_b,_Y) = sess.run((W,b,Y)) #一次run三個ts變數
    print('W =', _W)
    print('b =', _b)
    print('Y =', _Y)

W = [[ 0.64384288  1.22899091]
 [-0.39720941  0.68059981]
 [ 0.43061957  0.67745006]]
b = [[-1.24221337  1.11834407]]
Y = [[ 0.          2.01704025]]


In [13]:
#以placeholder傳入X值
X = tf.placeholder('float', [None, 3])
W = tf.random_normal([3, 2])
b = tf.random_normal([1, 2])
Y = tf.nn.relu(tf.matmul(X,W)+b)

In [14]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = [[0.4, 0.2, 0.4]]
    (_X,_W,_b,_Y) = sess.run((X,W,b,Y), feed_dict={X:X_array})
    print('X =\n', _X)
    print('W =\n', _W)
    print('b =\n', _b)
    print('Y =\n', _Y)

X =
 [[ 0.40000001  0.2         0.40000001]]
W =
 [[ 1.36824942 -1.38696539]
 [ 0.85981923 -1.21334791]
 [-0.2470956  -0.12866341]]
b =
 [[ 0.37683281 -0.73466474]]
Y =
 [[ 0.99725831  0.        ]]


In [15]:
#傳入3*3的X_array
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    X_array = [[0.4, 0.2, 0.4],
               [0.3, 0.4, 0.5],
               [0.3,-0.4, 0.5]]
    (_X,_W,_b,_Y) = sess.run((X,W,b,Y), feed_dict={X:X_array})
    print('X =\n', _X)
    print('W =\n', _W)
    print('b =\n', _b)
    print('Y =\n', _Y)

X =
 [[ 0.40000001  0.2         0.40000001]
 [ 0.30000001  0.40000001  0.5       ]
 [ 0.30000001 -0.40000001  0.5       ]]
W =
 [[-1.57733417 -0.64000994]
 [ 0.50249869  1.54552114]
 [-1.48083115 -0.35752282]]
b =
 [[ 2.0504725   0.96246105]]
Y =
 [[ 0.927706    0.87255216]
 [ 1.0378561   1.20990515]
 [ 0.63585711  0.        ]]
