In [1]:
# Numpy Array 介紹：
# https://blog.aweimeow.tw/2016/10/23/numpy-%E7%9A%84-array-%E4%BB%8B%E7%B4%B9/

In [2]:
import numpy as np

In [3]:
# 宣告一個 2*3 的二維陣列，資料型態為 int16
x = np.array([[1, 2, 3], [4, 5, 6]], np.int16)

In [4]:
# ndarray = N-dimensional array
type(x)

numpy.ndarray

In [5]:
x.shape

(2, 3)

In [6]:
x.dtype

dtype('int16')

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [8]:
# 取得維度1的第一個陣列
x[0]

array([1, 2, 3], dtype=int16)

In [9]:
# 取得維度1第一個陣列中的第一筆資料
x[0][0]

1

In [10]:
# ndarray.reshape(shape): 把同樣的資料以不同的 shape 輸出，array 的 total size 要相同
y = x.reshape((3, 2))
y

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)

In [11]:
# ndarray.flatten(): 把多維陣列轉成一維陣列（扁平化＆Copy）
# ndarray.ravel(): 回傳扁平化的陣列（無Copy）
z = x.flatten()
z

array([1, 2, 3, 4, 5, 6], dtype=int16)

In [12]:
# 取的執行檔的相對路徑
import os
relative_path = os.path.dirname('__file__')

In [13]:
# nmmpy array save and load method
# https://stackoverflow.com/questions/28439701/how-to-save-and-load-numpy-array-data-properly

In [14]:
# save and load a [text file]
# 設定存檔的位置
filename = os.path.join(relative_path, 'Data/ndarray.txt')

In [17]:
# 存檔
np.savetxt(filename, x, fmt='%d')

In [21]:
# 讀檔
a = np.loadtxt(filename, dtype=int)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# save and load a [binary file]
# 設定存檔的位置
filename = os.path.join(relative_path, 'Data/ndarray.dat')

In [32]:
# 存檔
x.tofile(filename)

In [33]:
# 讀檔
b = np.fromfile(filename, dtype=np.int16)
b

array([1, 2, 3, 4, 5, 6], dtype=int16)

In [39]:
# save and load a [platform independent format file]
# 設定存檔的位置
filename = os.path.join(relative_path, 'Data/ndarray.npy')

In [40]:
# 存檔
np.save(filename, x)

In [41]:
# 讀檔
c = np.load(filename)
c

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)