In [1]:
import tensorflow as tf

In [2]:
#建立計算圖
ts_c = tf.constant(2, name='ts_c')
ts_v = tf.Variable(ts_c+5, name='ts_v')

In [3]:
ts_c

<tf.Tensor 'ts_c:0' shape=() dtype=int32>

In [4]:
ts_v

<tf.Variable 'ts_v:0' shape=() dtype=int32_ref>

In [5]:
#執行計算圖
#使用with自動關閉session
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('ts_c =', sess.run(ts_c))
    print('ts_v =', sess.run(ts_v))

ts_c= 2
ts_v= 7


In [6]:
#執行計算圖階段才設定數值，須使用placeholder
#以下計算圖用來計算面積
width = tf.placeholder('int32')
height = tf.placeholder('int32')
area = tf.multiply(width, height)

In [7]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('area =', sess.run(area, feed_dict={width:6, height:8}))

area= 48


In [8]:
#建立一維張量(tensor)
ts_x = tf.Variable([0.1, 0.2, 0.3])

In [9]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    x = sess.run(ts_x)
    print(x)

[ 0.1         0.2         0.30000001]


In [10]:
x.shape

(3,)

In [11]:
#建立二維張量(tensor)
ts_y = tf.Variable([[1,2,3]])

In [14]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    y = sess.run(ts_y)
    print(y)

[[1 2 3]]


In [15]:
y.shape

(1, 3)

In [17]:
#矩陣乘法:X.shape(1,3) * W.shape(3,2)
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])
XW = tf.matmul(X, W)

In [18]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(XW))

[[-1.29999995  0.40000001]]


In [19]:
#矩陣加法:b.shape(1,2) + XW.shape(1,2)
b = tf.Variable([[0.1,0.2]])
XW = tf.Variable([[-1.3, 0.4]])
Sum = b + XW

In [20]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print(sess.run(Sum))

[[-1.19999993  0.60000002]]


In [21]:
#矩陣乘法與加法
X = tf.Variable([[1.,1.,1.]])
W = tf.Variable([[-0.5, -0.2],
                 [-0.3, 0.4],
                 [-0.5, 0.2]])
b = tf.Variable([[0.1,0.2]])
XWb = tf.matmul(X,W) + b

In [22]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    print('XWb=', sess.run(XWb))

XWb= [[-1.19999993  0.60000002]]
